language: python
python:
  - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
before_install:
  - pip install poetry
install:
  - poetry install
script: poetry run make check
after_success: coveralls
notifications:
  email: false