if: >  # Forbid running non-PR pushes from pyup bot
  not (type != pull_request AND branch =~ ^pyup\-scheduled\-update\-)

dist: xenial
sudo: required

language: python
python:
  - 3.6
  - 3.7
before_install:
  - pip install codecov
  - pip install poetry
install:
  - poetry install
script: poetry run make check
after_success: codecov
notifications:
  email: false